### ISSUE TITLE
Weekend Frontend ₦10k Challenge: Make this Responsive

### ISSUE THREAD

**Issue by mykeels** [mykeels/tic-tac-toe#2]
# Problem

This design looks great on desktop screens. However, on smaller screens (see screenshots below), the layout is broken. 

## Challenge

Fix the layout for the following screens:

- iPad
- iPhone 6/7/8 Plus or Galaxy S5

while keeping the desktop view on point.

## For Contestants

- Fork this repository
- Assign this issue to yourself or Comment, so I know you are working on it.
- Create a PR early, even if it is a draft, so I can follow your progress.
- Ask questions on this thread, [or reach out on twitter](https://twitter.com/mykeels).
- Show design concept before writing code with screenshots in the PR.
- Provide screenshots of the final results for the different screens, exactly like I have done below in your PR.
- Complete this by 11:59pm on Sunday, 24th May, 2020.
- The person behind the first merged PR gets ₦10,000 from me.

## Additional Context

The app is built with Angular JS, so it might appear a daunting task. These two files can serve as your starting point.

- [index.html](https://github.com/mykeels/tic-tac-toe/blob/master/src/index.html)
- [style.css](https://github.com/mykeels/tic-tac-toe/blob/master/src/css/style.css)

The tic-tac-toe board scales up from 3x3 to 10x10, so make sure they all display well in your design. Your screenshots should show 10x10 though (feel free to add others).

Feel free to upgrade the bootstrap, switch to tailwind, or go wild by using hand-crafted CSS.

Make us proud ❤️

## Screenshots

- Desktop

![image](https://user-images.githubusercontent.com/11996508/82652811-260fba80-9c16-11ea-96f9-c1892540b02a.png)

- iPad (current)

![image](https://user-images.githubusercontent.com/11996508/82652870-40e22f00-9c16-11ea-8756-3524231edd6a.png)

- iPhone 6/7/8 Plus (current)

![image](https://user-images.githubusercontent.com/11996508/82652924-5a837680-9c16-11ea-9d7c-3a9ab8ba97ae.png)

**Comment by oneEyedSunday** [comment]
Here goes nothing ⌛️

**Comment by Chimdiya1** [comment]
Hi, what do you mean by "Show design concept before writing code with screenshots in the PR."

**Comment by mykeels** [comment]
@Chimdiya1 it's so we're on the same page on what you want to design. 

Using a prototyping tool, or even a rough sketch on paper, you could show the layout you intend for the different screens.

**Comment by Chimdiya1** [comment]
> @Chimdiya1 it's so we're on the same page on what you want to design.
> 
> Using a prototyping tool, or even a rough sketch on paper, you could show the layout you intend for the different screens.

well then, here is a link to the the layout I intend to use. https://www.figma.com/file/nAsxVl369WBniXf5sEVTcb/tic-tac-toe-challenge?node-id=1%3A831

**Comment by Olusamimaths** [comment]
@mykeels Check out my PR (draft) with screenshots of my designs https://github.com/mykeels/tic-tac-toe/pull/3

**Comment by oneEyedSunday** [comment]
Something #5

**Comment by mykeels** [comment]
I'll be merging in this PR. 

Thanks, @Chimdiya1

Thanks, everyone for participating.

https://github.com/mykeels/tic-tac-toe/pull/4
